"""Turns retrieved RAG chunks into a natural-language answer, via Sarvam's chat completion API --
the same LLM/pattern already used by summary_service.py and normalization_service.py.

Citations are NEVER generated by this service or the LLM -- they're built separately, directly
from chunk metadata, by ask_janmitra_service.py (see that module). This service's prompt (see
prompts/ask_janmitra_system_prompt.txt) explicitly instructs the model not to write its own
source list, specifically to prevent an LLM from inventing a URL/phone number that sounds
plausible but isn't in the retrieved context.

Graceful degradation, not a hard failure: if the LLM is unconfigured or the call fails, this
falls back to a simple template built directly from the retrieved chunks' own text -- Ask
Sarthi must keep working (with real, sourced content, just not LLM-polished prose) even
without a working LLM connection, matching this codebase's existing pattern
(normalization_service.py falls back to the original text the same way).
"""

import logging

import httpx
from sarvamai import SarvamAI

from backend.config import get_prompt, settings

logger = logging.getLogger(__name__)

# Real Sarvam pricing for sarvam-105b (confirmed directly against Sarvam's own docs,
# https://docs.sarvam.ai/api/getting-started/pricing, checked 2026-08-26): Rs29.28/1M input
# tokens, Rs73.2/1M output tokens (cached-input pricing, Rs10.98/1M, isn't used here -- Sarvam's
# own SDK response never reports a cached-token count for this model, see generate()'s own
# `usage.prompt_tokens_details` check below).
#
# Reported directly in real Indian Rupees, NOT converted to USD -- a deliberate choice: this app's
# actual Sarvam bill is in Rupees, and a live INR->USD conversion would just add a second,
# constantly-drifting approximation on top of an already-tiny per-request number. Phoenix's own
# dashboard hardcodes a literal "$" prefix on this column regardless of what currency the number
# actually is (it has no INR/₹ display mode) -- that "$" is simply wrong/ignorable, the number
# itself is the real, correct Rupee amount.
_SARVAM_INPUT_COST_PER_TOKEN_INR = 29.28 / 1_000_000
_SARVAM_OUTPUT_COST_PER_TOKEN_INR = 73.2 / 1_000_000

# This task is grounded-context QA, not creative generation -- the system prompt already demands
# the model state only facts present in the retrieved context (prompts/ask_janmitra_system_prompt.txt),
# and a lower temperature makes its output more consistently literal to that context rather than
# sampling more freely around it. Confirmed `temperature` is a real, accepted parameter for this
# exact model via the installed sarvamai SDK's own ChatClient.completions() signature -- not every
# reasoning model honors this parameter (some ignore/reject it), so this was checked directly
# rather than assumed. Deliberately not also touching `top_p` in the same change -- moving one
# sampling parameter at a time keeps any observed quality effect attributable to a specific cause.
_ANSWER_TEMPERATURE = 0.2


class AnswerGenerationService:
    def __init__(self) -> None:
        self._client: SarvamAI | None = None
        if settings.LLM_API_KEY:
            # See config.py's SARVAM_CONNECT_TIMEOUT_SECONDS docstring: this reasoning-model call
            # needs a generous read timeout (legitimate slow-but-working answers shouldn't be cut
            # off), but still fails fast on a genuinely dead connection.
            timeout = httpx.Timeout(
                connect=settings.SARVAM_CONNECT_TIMEOUT_SECONDS,
                read=settings.SARVAM_REASONING_READ_TIMEOUT_SECONDS,
                write=settings.SARVAM_REASONING_READ_TIMEOUT_SECONDS,
                pool=settings.SARVAM_REASONING_READ_TIMEOUT_SECONDS,
            )
            self._client = SarvamAI(api_subscription_key=settings.LLM_API_KEY, timeout=timeout)
        else:
            logger.warning("LLM_API_KEY is not set; Ask Sarthi will fall back to raw excerpts, not LLM-generated prose.")

    def generate(
        self, question: str, context_chunks: list[str], language_name: str,
        context_labels: list[str] | None = None,
    ) -> tuple[str, bool, dict[str, int | float] | None]:
        """Returns (answer_text, was_llm_generated, token_usage). was_llm_generated=False means
        the fallback template was used (LLM unconfigured or the call failed) -- callers/tests can
        assert on this rather than guessing from the text shape. `token_usage` is
        `{"prompt_tokens", "completion_tokens", "total_tokens"}` straight from Sarvam's own
        response (real usage, not estimated), plus `{"prompt_cost_inr", "completion_cost_inr",
        "total_cost_inr"}` computed from that same real token count against Sarvam's own published
        price, in real Indian Rupees -- not converted to USD (see
        `_SARVAM_INPUT_COST_PER_TOKEN_INR`'s own comment for why) -- all six only when the LLM was
        actually called, `None` on the fallback path (no LLM call happened, so nothing to report,
        no cost incurred) -- consumed by `orchestration/nodes.py` to populate Phoenix's Metrics
        view (see `observability/tracing.py`'s `_phoenix_end_span()`), purely observability, never
        used for any routing/business logic.

        `context_labels`, if given, must be the same length as `context_chunks` -- one short
        "VERIFIED | Topic: ..." label per chunk (see rag_retriever.chunk_context_label), shown to
        the LLM alongside that chunk's content so it can tell a topically-mismatched-but-
        same-category record apart from one that actually answers the question (see that
        function's own docstring for the live Bhubaneswar case this closes). Optional and
        defaults to None so any caller not yet passing it keeps behaving exactly as before.
        Deliberately NOT folded into `context_chunks` itself: `_fallback_answer` echoes a chunk's
        content verbatim when no LLM is available, and must never leak this internal label into a
        citizen-facing answer."""
        if context_labels:
            prompt_chunks = [f"[{label}]\n{chunk}" for label, chunk in zip(context_labels, context_chunks)]
        else:
            prompt_chunks = context_chunks
        context = "\n\n---\n\n".join(prompt_chunks)

        if self._client is None:
            return self._fallback_answer(context_chunks), False, None

        try:
            system_prompt = get_prompt("ask_janmitra_system_prompt.txt")
            prompt_template = get_prompt("ask_janmitra_answer_prompt.txt")
            prompt = prompt_template.format(question=question, context=context, language_name=language_name)

            response = self._client.chat.completions(
                model=settings.LLM_MODEL,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=settings.LLM_MAX_TOKENS,
                reasoning_effort="low",
                temperature=_ANSWER_TEMPERATURE,
            )
            choice = response.choices[0]
            content = choice.message.content
            if not content or not content.strip():
                logger.warning(
                    "Ask Sarthi answer generation returned no content (finish_reason=%s); falling back to raw excerpts.",
                    choice.finish_reason,
                )
                return self._fallback_answer(context_chunks), False, None
            # Deliberately its own inner try/except, separate from the outer one below: a real
            # answer was already successfully generated by this point, so a problem extracting
            # USAGE data (a malformed/unexpected response shape) must only cost the token/cost
            # observability for this one turn, never throw away a real, working answer and
            # silently replace it with the fallback -- that would be a strictly worse outcome for
            # the citizen than just missing some Metrics data.
            token_usage: dict[str, int | float] | None = None
            try:
                usage = getattr(response, "usage", None)
                if usage is not None:
                    prompt_cost = usage.prompt_tokens * _SARVAM_INPUT_COST_PER_TOKEN_INR
                    completion_cost = usage.completion_tokens * _SARVAM_OUTPUT_COST_PER_TOKEN_INR
                    token_usage = {
                        "prompt_tokens": usage.prompt_tokens,
                        "completion_tokens": usage.completion_tokens,
                        "total_tokens": usage.total_tokens,
                        "prompt_cost_inr": prompt_cost,
                        "completion_cost_inr": completion_cost,
                        "total_cost_inr": prompt_cost + completion_cost,
                    }
            except Exception:
                logger.warning("Ask Sarthi answer generation: could not read token usage from the response (answer itself still succeeded).", exc_info=True)
            return content.strip(), True, token_usage
        except Exception as exc:
            logger.warning("Ask Sarthi answer generation failed, falling back to raw excerpts: %s", exc, exc_info=True)
            return self._fallback_answer(context_chunks), False, None

    @staticmethod
    def _fallback_answer(context_chunks: list[str]) -> str:
        if not context_chunks:
            return "I don't have information on this yet."
        # LIVE PRODUCT FINDING: a knowledge record is split into several retrieval chunks by
        # field family (see scripts/build_rag_knowledge_base.py's chunk_document()) -- one of
        # which is FAQ-only, deterministically rendered as "Q: <question> A: <answer>" for every
        # FAQ item on that record. When that FAQ chunk happens to score highest, this fallback
        # used to echo it verbatim -- reading as a raw "Q: A:" dump that answers a DIFFERENT
        # question (usually "is this data verified?") than the one the citizen actually asked,
        # never a proper-looking response. Prefer the first chunk that ISN'T FAQ-shaped -- the
        # "Q: " prefix is this app's own deterministic chunk format, not a heuristic over
        # free-form content, so this never misclassifies real prose. Falls back to the FAQ chunk
        # only when literally nothing else was retrieved -- still better than no answer at all.
        for chunk in context_chunks:
            if not chunk.lstrip().startswith("Q: "):
                return chunk
        return context_chunks[0]
