import { Fragment, useMemo, useState } from "react";
import { t, type LangCode } from "../lib/i18n";
import { localizeCityName, localizeStateName } from "../lib/locationNames";
import type { LocationStatusCount } from "../lib/api";

type StatusKey = "pending" | "assigned" | "accepted" | "in_progress" | "resolved";
const STATUS_ORDER: StatusKey[] = ["pending", "assigned", "accepted", "in_progress", "resolved"];
const STATUS_COLOR: Record<StatusKey, string> = {
  pending: "var(--status-pending)",
  assigned: "var(--status-open)",
  accepted: "var(--status-progress)",
  in_progress: "var(--status-progress)",
  resolved: "var(--status-resolved)",
};

// Ward names are free text typed per-complaint (Complaint.ward, not a foreign key into the wards
// table), not a fixed list like states/districts -- India has 90,000+ real wards, so there is no
// finite table that could ever cover them all. Translated here are only the exact ward strings
// today's real demo complaints actually use; the "*Test Ward <id>" entries under the "Unknown"
// bucket are QA/test artifacts, not real production wards, and are left as-is since there's
// nothing meaningful to translate in an autogenerated id. Any ward text not in this table (a new
// real complaint's ward, or a test one) falls back to the raw string, same as before.
const WARD_NAME_TRANSLATIONS: Record<string, Partial<Record<LangCode, string>>> = {
  "Ward 3 — Indiranagar, Bengaluru": {
    hi: "वार्ड 3 — इंदिरानगर, बेंगलुरु",
    mr: "वॉर्ड 3 — इंदिरानगर, बेंगळुरू",
    or: "ୱାର୍ଡ 3 — ଇନ୍ଦିରାନଗର, ବେଙ୍ଗାଲୁରୁ",
    gu: "વોર્ડ 3 — ઈન્દિરાનગર, બેંગલુરુ",
    bn: "ওয়ার্ড ৩ — ইন্দিরানগর, বেঙ্গালুরু",
  },
  "Ward 42 — Malad, Mumbai": {
    hi: "वार्ड 42 — मलाड, मुंबई",
    mr: "वॉर्ड 42 — मलाड, मुंबई",
    or: "ୱାର୍ଡ 42 — ମାଲାଡ, ମୁମ୍ବାଇ",
    gu: "વોર્ડ 42 — મલાડ, મુંબઈ",
    bn: "ওয়ার্ড ৪২ — মালাড, মুম্বই",
  },
  "Ward 11 — Navrangpura, Ahmedabad": {
    hi: "वार्ड 11 — नवरंगपुरा, अहमदाबाद",
    mr: "वॉर्ड 11 — नवरंगपुरा, अहमदाबाद",
    or: "ୱାର୍ଡ 11 — ନବରଙ୍ଗପୁରା, ଅହମ୍ମଦାବାଦ",
    gu: "વોર્ડ 11 — નવરંગપુરા, અમદાવાદ",
    bn: "ওয়ার্ড ১১ — নবরংগপুরা, আহমেদাবাদ",
  },
  "Ward 25 — Egmore, Chennai": {
    hi: "वार्ड 25 — एग्मोर, चेन्नई",
    mr: "वॉर्ड 25 — एग्मोर, चेन्नई",
    or: "ୱାର୍ଡ 25 — ଏଗମୋର, ଚେନ୍ନାଇ",
    gu: "વોર્ડ 25 — એગ્મોર, ચેન્નાઈ",
    bn: "ওয়ার্ড ২৫ — এগমোর, চেন্নাই",
  },
  "Ward 1 — Chowk, Lucknow": {
    hi: "वार्ड 1 — चौक, लखनऊ",
    mr: "वॉर्ड 1 — चौक, लखनौ",
    or: "ୱାର୍ଡ 1 — ଚୌକ, ଲକ୍ଷ୍ନୌ",
    gu: "વોર્ડ 1 — ચોક, લખનૌ",
    bn: "ওয়ার্ড ১ — চক, লখনউ",
  },
  "Ward 6 — Salt Lake, Kolkata": {
    hi: "वार्ड 6 — साल्ट लेक, कोलकाता",
    mr: "वॉर्ड 6 — साल्ट लेक, कोलकाता",
    or: "ୱାର୍ଡ 6 — ସଲ୍ଟ ଲେକ, କୋଲକାତା",
    gu: "વોર્ડ 6 — સોલ્ટ લેક, કોલકાતા",
    bn: "ওয়ার্ড ৬ — সল্ট লেক, কলকাতা",
  },
};

function localizeName(name: string, lang: LangCode): string {
  if (name === "Unassigned") return t(lang, "admin.locUnassigned");
  const state = localizeStateName(name, lang);
  if (state !== name) return state;
  const city = localizeCityName(name, lang);
  if (city !== name) return city;
  return WARD_NAME_TRANSLATIONS[name]?.[lang] ?? name;
}

type Counts = Partial<Record<StatusKey, number>>;
interface WardNode {
  total: number;
  counts: Counts;
}
interface DistrictNode {
  total: number;
  wards: Record<string, WardNode>;
}
interface StateNode {
  total: number;
  districts: Record<string, DistrictNode>;
}

/** Builds the 3-level state -> district -> ward tree the drill-down renders from the flat rows
 * GET /admin/complaints/by-location returns (one row per state/district/ward/status combo). */
function buildTree(rows: LocationStatusCount[]): Record<string, StateNode> {
  const tree: Record<string, StateNode> = {};
  for (const row of rows) {
    const state = (tree[row.state] ??= { total: 0, districts: {} });
    const district = (state.districts[row.district] ??= { total: 0, wards: {} });
    const ward = (district.wards[row.ward] ??= { total: 0, counts: {} });
    const key = row.status as StatusKey;
    ward.counts[key] = (ward.counts[key] || 0) + row.total;
    ward.total += row.total;
    district.total += row.total;
    state.total += row.total;
  }
  return tree;
}

function sumCounts(counts: Counts): number {
  return Object.values(counts).reduce((a, b) => a + (b || 0), 0);
}

function aggregateWards(wards: Record<string, WardNode>): Counts {
  const out: Counts = {};
  for (const w of Object.values(wards)) {
    for (const key of STATUS_ORDER) {
      if (w.counts[key]) out[key] = (out[key] || 0) + (w.counts[key] || 0);
    }
  }
  return out;
}

function aggregateDistricts(districts: Record<string, DistrictNode>): Counts {
  const out: Counts = {};
  for (const d of Object.values(districts)) {
    const wardTotals = aggregateWards(d.wards);
    for (const key of STATUS_ORDER) {
      if (wardTotals[key]) out[key] = (out[key] || 0) + (wardTotals[key] || 0);
    }
  }
  return out;
}

function StatusBar({ counts, statusLabel }: { counts: Counts; statusLabel: (status: StatusKey) => string }) {
  const total = sumCounts(counts) || 1;
  return (
    <div className="loc-bar">
      {STATUS_ORDER.filter((k) => counts[k]).map((k) => (
        <span
          key={k}
          style={{ width: `${((counts[k] || 0) / total) * 100}%`, background: STATUS_COLOR[k] }}
          title={`${statusLabel(k)}: ${counts[k]}`}
        />
      ))}
    </div>
  );
}

function Chevron() {
  return (
    <svg className="loc-chev" width="16" height="16" viewBox="0 0 24 24" fill="none">
      <path d="M9 6l6 6-6 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

interface Props {
  rows: LocationStatusCount[];
  lang: LangCode;
  statusLabel: (status: StatusKey) => string;
}

/** Admin dashboard's "complaints by location" widget: a clickable state -> district -> ward
 * drill-down, each row showing a status breakdown bar. Clicking a row replaces the list with its
 * children (breadcrumb-style, one path visible at a time) -- picked over an always-expanded tree
 * for a shorter, always-shallow list, matching the picked Draft B mock. */
export default function LocationHierarchyPanel({ rows, lang, statusLabel }: Props) {
  const tree = useMemo(() => buildTree(rows), [rows]);
  const [path, setPath] = useState<string[]>([]);

  const crumbs: { label: string; path: string[] }[] = [{ label: t(lang, "admin.locAllStates"), path: [] }];
  if (path[0]) crumbs.push({ label: localizeName(path[0], lang), path: [path[0]] });
  if (path[1]) crumbs.push({ label: localizeName(path[1], lang), path: [path[0], path[1]] });

  const isEmpty = Object.keys(tree).length === 0;
  let rowsEl: React.ReactNode = null;

  if (!isEmpty && path.length === 0) {
    const states = Object.entries(tree).sort((a, b) => b[1].total - a[1].total);
    rowsEl = states.map(([name, s]) => (
      <button key={name} className="loc-row" onClick={() => setPath([name])}>
        <span className="loc-name">{localizeName(name, lang)}</span>
        <span className="loc-bar-wrap">
          <StatusBar counts={aggregateDistricts(s.districts)} statusLabel={statusLabel} />
        </span>
        <span className={`loc-count mono${s.total === 0 ? " zero" : ""}`}>{s.total}</span>
        <Chevron />
      </button>
    ));
  } else if (!isEmpty && path.length === 1) {
    const state = tree[path[0]];
    const districts = state ? Object.entries(state.districts).sort((a, b) => b[1].total - a[1].total) : [];
    rowsEl = districts.map(([name, d]) => (
      <button key={name} className="loc-row" onClick={() => setPath([path[0], name])}>
        <span className="loc-name">{localizeName(name, lang)}</span>
        <span className="loc-bar-wrap">
          <StatusBar counts={aggregateWards(d.wards)} statusLabel={statusLabel} />
        </span>
        <span className={`loc-count mono${d.total === 0 ? " zero" : ""}`}>{d.total}</span>
        <Chevron />
      </button>
    ));
  } else if (!isEmpty) {
    const district = tree[path[0]]?.districts[path[1]];
    const wards = district ? Object.entries(district.wards).sort((a, b) => b[1].total - a[1].total) : [];
    rowsEl = wards.map(([name, w]) => (
      <div key={name} className="loc-row leaf">
        <span className="loc-name" title={name}>
          {localizeName(name, lang)}
        </span>
        <span className="loc-bar-wrap">
          <StatusBar counts={w.counts} statusLabel={statusLabel} />
        </span>
        <span className={`loc-count mono${w.total === 0 ? " zero" : ""}`}>{w.total}</span>
      </div>
    ));
  }

  return (
    <div className="admin-loc-ai-body">
      <div className="loc-crumbs">
        {crumbs.map((c, i) => (
          <Fragment key={i}>
            {i > 0 && <span className="loc-crumb-sep">/</span>}
            <button
              className={`loc-crumb-btn ${i === crumbs.length - 1 ? "current" : ""}`}
              disabled={i === crumbs.length - 1}
              onClick={() => setPath(c.path)}
            >
              {c.label}
            </button>
          </Fragment>
        ))}
      </div>
      <div className="loc-list-box">
        <div className="loc-list">{isEmpty ? <div className="loc-empty">{t(lang, "admin.noComplaints")}</div> : rowsEl}</div>
      </div>
      <div className="loc-legend">
        {STATUS_ORDER.map((k) => (
          <span key={k}>
            <i style={{ background: STATUS_COLOR[k] }} />
            {statusLabel(k)}
          </span>
        ))}
      </div>
    </div>
  );
}
