"""Builds the RAG retrieval index: chunks.json -> real embeddings -> ChromaDB (persistent).

Reads ONLY data/rag_knowledge_base/chunks/chunks.json (already generated by
scripts/build_rag_knowledge_base.py from the hand-authored knowledge_records/ — this script does
NOT read knowledge_records/ directly and does not regenerate documents/chunks; run
build_rag_knowledge_base.py first if the underlying knowledge records changed).

Default path: embeds every chunk with `SentenceTransformerEmbeddingProvider`
(intfloat/multilingual-e5-small) and upserts into the persistent ChromaDB collection at
`settings.CHROMA_PERSIST_DIR` (see backend/config.py) — this is the active production retrieval
path (see docs/ask_sarthi_rag_architecture.md).

Safe to rerun: every chunk is upserted by its stable `chunk_id` (see
backend/services/vector_store.py's ChromaVectorStore.upsert docstring) — re-running after no
knowledge-base change is a no-op content-wise (same IDs, same vectors, overwritten in place, no
duplicates); re-running after a knowledge-base change updates exactly the chunks that changed.

--legacy-tfidf: builds the OLD flat-file TF-IDF index instead (data/rag_knowledge_base/
embeddings/index.json) — kept only so the TF-IDF vs. real-embeddings comparison in the
architecture doc is reproducible; not part of the default/production path.

Usage:
    python scripts/build_rag_embeddings.py                # ChromaDB (default, production path)
    python scripts/build_rag_embeddings.py --legacy-tfidf  # old flat TF-IDF index (comparison only)
"""

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.config import settings


def _load_chunks() -> list[dict]:
    chunks_path = settings.RAG_DATA_DIR / "chunks" / "chunks.json"
    if not chunks_path.exists():
        raise SystemExit(
            f"{chunks_path} does not exist. Run 'python scripts/build_rag_knowledge_base.py' "
            f"first to generate it from knowledge_records/."
        )
    chunks = json.loads(chunks_path.read_text(encoding="utf-8"))
    print(f"Loaded {len(chunks)} chunks from {chunks_path}")
    return chunks


_METADATA_FIELDS = [
    "document_id", "state", "district", "city", "municipality", "zone", "ward", "area",
    "geographic_scope", "service_category", "service_id", "sub_service", "department",
    "source_id", "source_title", "source_organization", "source_url", "source_type",
    "verification_status",
]


def build_chroma_index() -> None:
    from backend.services.embedding_provider import SentenceTransformerEmbeddingProvider
    from backend.services.vector_store import ChromaVectorStore

    chunks = _load_chunks()

    t0 = time.perf_counter()
    provider = SentenceTransformerEmbeddingProvider()
    provider.load()  # force the (slow, first-time) load now, so it's not silently inside the batch-embed timing below
    load_seconds = time.perf_counter() - t0
    print(f"Loaded embedding model {provider.model_name} (dim={provider.dimension}) in {load_seconds:.1f}s")

    t0 = time.perf_counter()
    vectors = provider.embed_batch([c["content"] for c in chunks], is_query=False)
    embed_seconds = time.perf_counter() - t0
    print(f"Embedded {len(chunks)} chunk(s) in {embed_seconds:.2f}s "
          f"({embed_seconds / max(len(chunks), 1) * 1000:.1f}ms/chunk)")

    store = ChromaVectorStore(settings.CHROMA_PERSIST_DIR, settings.CHROMA_COLLECTION_NAME)
    store.load()
    before_count = store.size

    t0 = time.perf_counter()
    chunk_ids = [c["chunk_id"] for c in chunks]
    documents = [c["content"] for c in chunks]
    metadatas = [{field: c.get(field) for field in _METADATA_FIELDS} for c in chunks]
    store.upsert(chunk_ids, vectors, documents, metadatas)
    upsert_seconds = time.perf_counter() - t0

    after_count = store.size
    print(f"Upserted {len(chunks)} chunk(s) into Chroma collection "
          f"'{settings.CHROMA_COLLECTION_NAME}' in {upsert_seconds:.2f}s")
    print(f"Collection size: {before_count} -> {after_count} "
          f"({'no duplicates -- upsert is idempotent' if after_count == len(chunks) else 'unexpected count, check for stale/orphaned entries'})")
    print(f"Persisted at: {settings.CHROMA_PERSIST_DIR}")


def build_legacy_tfidf_index() -> None:
    from backend.services.embedding_provider import TfidfEmbeddingProvider

    chunks = _load_chunks()
    provider = TfidfEmbeddingProvider()

    t0 = time.perf_counter()
    provider.fit([c["content"] for c in chunks])
    fit_seconds = time.perf_counter() - t0
    print(f"Fit TF-IDF vocabulary: {provider.vocabulary_size} unique token(s) in {fit_seconds:.3f}s")

    t0 = time.perf_counter()
    indexed_chunks = []
    for chunk in chunks:
        vector = provider.embed(chunk["content"])
        indexed_chunks.append({
            "chunk_id": chunk["chunk_id"],
            "vector": vector,
            "metadata": {"content": chunk["content"], **{f: chunk.get(f) for f in _METADATA_FIELDS}},
        })
    embed_seconds = time.perf_counter() - t0
    print(f"Embedded {len(indexed_chunks)} chunk(s) in {embed_seconds:.3f}s "
          f"({embed_seconds / max(len(indexed_chunks), 1) * 1000:.2f}ms/chunk)")

    index_path = settings.RAG_EMBEDDINGS_INDEX_PATH
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(
        json.dumps({"idf": provider.idf, "chunks": indexed_chunks}, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"Wrote legacy TF-IDF index to {index_path} ({index_path.stat().st_size / 1024:.1f} KB)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--legacy-tfidf", action="store_true",
        help="Build the old flat-file TF-IDF index instead of ChromaDB (comparison only, not the production path).",
    )
    args = parser.parse_args()

    if args.legacy_tfidf:
        build_legacy_tfidf_index()
    else:
        build_chroma_index()


if __name__ == "__main__":
    main()
